{
    base     => '/book',
    title    => 'Raku++ Internals',
    tagline  => 'How a hand-written C++ implementation of Raku works — from source text to native code.',
    repo     => 'https://github.com/ash/rakupp',
    pdf      => 'Raku++-Internals.pdf',
    pdf-note => '386 pages',

    # A one-line description per chapter slug, shown on the contents page.
    # A slug with no entry simply shows its title.
    blurbs => {
        'preface'             => 'who this is for, and the conventions it uses',
        'what-it-is'          => 'the goals, the four run modes, the shape of the system',
        'shape-of-source'     => 'the file map, and how to navigate it',
        'classification'      => 'why neither LL nor LR describes this compiler',
        'lexer'               => 'tokens, significant whitespace, quotes, heredocs',
        'parser'              => 'recursive descent, a Pratt core, and no compile-time execution',
        'user-operators'      => 'live tables, precedence traits, and lexical rollback',
        'ast'                 => 'the node hierarchy, and fields that answer questions about syntax',
        'value'               => 'one fat tagged struct for every runtime value',
        'strings'             => 'the copy-on-write string, and the quadratic it removed',
        'interning'           => 'interned tags and packed-prefix name comparison',
        'numbers'             => 'native ints, bignums, rationals, and the spill between them',
        'containers'          => 'scopes, binding, and where sharing is broken on purpose',
        'tree-walk'           => 'eval, exec, and the per-thread execution registers',
        'calls'               => 'building arguments, activating a routine, binding parameters',
        'control-flow'        => 'return and friends without a C++ throw',
        'dispatch'            => 'subs, multis, the method ladder, and re-dispatch',
        'objects'             => 'classes, roles, mixins, and the meta-object surface',
        'lazy'                => 'infinite sequences, gather without coroutines, junctions',
        'node-specialization' => 'one optimisation, measured end to end',
        'regex-compile'       => 'a second recursive-descent compiler inside the runtime',
        'matcher'             => 'continuation passing, backtracking, and a step budget',
        'grammars'            => 'rules, packrat memoisation, actions, protos',
        'ltm'                 => 'ranking alternations by declarative prefix',
        'unicode'             => 'graphemes, normalization, collation — from pinned tables',
        'run-modes'           => 'one program through interpret, bundle, AOT and native',
        'codegen'             => 'AST to C++, calling the same runtime the interpreter calls',
        'optimizer'           => 'three passes, and three defaults that are not passes',
        'dispatch-compiled'   => 'what each call shape costs, and an analysis that was wrong',
        'slim'                => 'how a binary drops what the program cannot reach',
        'astserial'           => 'the binary AST format, and what invalidates a cache entry',
        'wasm'                => 'the same runtime in a browser tab, Live mode, and embedded editors',
        'modules'             => 'what use Foo actually does, and where it diverges',
        'nqp'                 => 'a compatibility subset that costs nothing when unused',
        'nativecall'          => 'libffi loaded at run time, and its ABI probed not tabulated',
        'extension-abi'       => 'the C ABI an extension compiles against, and why it never sees Value',
        'concurrency'         => 'the GIL, per-thread registers, and switching the lock off',
        'tooling'             => 'lint, highlight, profile, the REPL, and tools written in Raku',
        'measuring'           => 'the benchmark policy, the gates, and what did not pay',
        'appendix-a'          => 'the VT, NK and regex-node tag sets',
        'appendix-b'          => 'every flag and environment variable',
        'appendix-c'          => 'a source map, and the rules that are easy to break',
        'appendix-d'          => 'the compiler vocabulary, general and local, A to Z',
    },
}
