{
    title   => 'Rakumap',
    tagline => 'Machine-written Raku programs, each run under the reference compiler and under Raku++.',
    base    => '/map',
    map-src => '/Users/ash/rakumap',
    repo    => 'https://github.com/ash/rakumap',
    # Topics in reading order — the simplest ideas first. The key is the
    # generator's name without its -vN suffix.
    order   => <literals variables numeric operators control subs signatures containers
                types methods regex grammars unicode builtins phasers concurrency invalid>,
    topics  => {
        literals    => { title => 'Literals',
                         blurb => 'Writing values straight into code: numbers in other bases, rationals, pairs, strings, versions.' },
        variables   => { title => 'Variables',
                         blurb => 'Assignment, binding, scope, state variables and dynamic variables.' },
        numeric     => { title => 'Numbers',
                         blurb => 'Integers, rationals, floating point, complex numbers and infinities, mixed together.' },
        operators   => { title => 'Operators',
                         blurb => 'Arithmetic, comparison, junctions and reductions over the same pair of values.' },
        control     => { title => 'Control flow',
                         blurb => 'if and unless, loops, given/when, gather/take and early returns.' },
        subs        => { title => 'Subroutines',
                         blurb => 'Declaring and calling subs, closures and recursion.' },
        signatures  => { title => 'Signatures',
                         blurb => 'How arguments bind to parameters: defaults, named, slurpy, typed and multi subs.' },
        containers  => { title => 'Arrays and hashes',
                         blurb => 'Arrays, hashes and scalar containers: what gets copied, what gets shared, what flattens.' },
        types       => { title => 'Types',
                         blurb => 'Type objects, roles, enums, subsets and smartmatching against types.' },
        methods     => { title => 'Classes and methods',
                         blurb => 'Attributes, inheritance, roles, private and multi methods, delegation.' },
        regex       => { title => 'Regexes',
                         blurb => 'Matching, captures, quantifiers, comb, split and subst.' },
        grammars    => { title => 'Grammars and match trees',
                         blurb => 'Grammars assembled at random from alternations, quantifiers, subrule calls and captures, with every field of the resulting Match printed.' },
        unicode     => { title => 'Unicode',
                         blurb => 'Characters versus codepoints, case mapping and text outside ASCII.' },
        builtins    => { title => 'Built-in functions',
                         blurb => 'Everyday routines: abs and sqrt, sort, unique, zip, rotor, sprintf and friends.' },
        phasers     => { title => 'Phasers',
                         blurb => 'Code that runs at a particular moment: BEGIN, INIT, END, ENTER, LEAVE, FIRST, LAST, CATCH.' },
        concurrency => { title => 'Concurrency',
                         blurb => 'Promises, start/await, channels, supplies, locks and threads — small and bounded.' },
        invalid     => { title => 'Programs that must fail',
                         blurb => 'Deliberately broken code. The correct result is a compile-time error, not output.' },
    },
}
