#!/usr/bin/env raku
# divergences.raku — turn the behaviour matrix into a defect report.
#
#   rakupp tools/divergences.raku            # -> DIVERGENCES.md
#
# Reads src/data/matrix.raku (built by tools/matrix.raku, which runs every
# operator against the same operand battery on both interpreters) and groups the
# disagreements by root cause, so the output is a fix list rather than 300
# separate observations.

# Matrix results are recorded as "Type | gist", and the keys as "cat|sym" — so
# almost every cell contains a pipe. In a Markdown table a bare pipe ends the
# cell, even inside a code span, so each one has to be escaped.
sub cell(Str $s --> Str) { $s.subst('|', '\\|', :g) }

# "Int | 1" -> "Int — 1"; keeps the type/value split readable without a pipe.
sub result(Str $s is copy --> Str) {
    return '_error:_ ' ~ cell($s.subst(/ ^ 'ERR ' /, '').substr(0, 72)) if $s.starts-with('ERR');
    $s = $s.subst(' | ', ' — ');
    '`' ~ cell($s.substr(0, 72)) ~ '`'
}

sub opname(Str $key --> Str) {
    my ($cat, $sym) = $key.split('|', 2);
    '`' ~ $cat ~ ':<' ~ cell($sym) ~ '>`'
}

# The probe records "Type | gist", but a Junction gist contains ` | ` itself —
# and under the autothreading defect so does the *type*, e.g.
# `any(Int | any(1, 2), Int | any(1, 2))`. Absorb parts until the parentheses
# balance, then name that shape for what it is rather than reporting `any(Int`.
sub type-of(Str $s --> Str) {
    return 'ERR' if $s.starts-with('ERR');
    my @parts = $s.split(' | ');
    my $t = @parts[0];
    my $i = 1;
    while $i < @parts.elems && $t.comb('(').elems != $t.comb(')').elems {
        $t ~= ' | ' ~ @parts[$i];
        $i++;
    }
    $t.contains(' | ') ?? 'Junction (autothreaded name)' !! $t
}

sub MAIN(Str :$matrix = 'src/data/matrix.raku', Str :$out = 'DIVERGENCES.md') {
    my %m = EVAL slurp $matrix;

    my @all;
    for %m.kv -> $key, @rows {
        for @rows -> @r {
            next unless @r[3] eq 'differ';
            @all.push([$key, @r[0], @r[1], @r[2]]);
        }
    }

    # Root-cause buckets, most-populous first.
    my %cluster;
    for @all -> @d {
        my ($key, $expr, $ku, $ra) = @d[0], @d[1], @d[2], @d[3];
        my $why = do if $ku.starts-with('ERR') { 'Raku++ rejects what Rakudo accepts' }
                  elsif $ra.contains('Cannot convert string to number') {
                      'Raku++ silently numifies a non-numeric string' }
                  elsif $ra.starts-with('ERR') { 'Raku++ accepts what Rakudo rejects' }
                  elsif type-of($ku) ne type-of($ra) { 'Result type differs' }
                  else { 'Result value differs' };
        %cluster{$why} //= [];
        %cluster{$why}.push([$key, $expr, $ku, $ra]);
    }

    # The type mismatches collapse hardest, so lead with that summary.
    my %pat;
    my %ex;
    for @all -> @d {
        next if @d[2].starts-with('ERR') || @d[3].starts-with('ERR');
        my ($a, $b) = type-of(@d[2]), type-of(@d[3]);
        next if $a eq $b;
        %pat{"$a\t$b"}++;
        %ex{"$a\t$b"} //= @d[1];
    }

    my @l;
    @l.push('# Raku++ / Rakudo divergences');
    @l.push('');
    @l.push('Generated by `tools/divergences.raku` from the behaviour matrix: every operator');
    @l.push('run against the same battery of operand types on both interpreters. Rows where');
    @l.push('both engines reject the expression count as agreement, however differently they');
    @l.push('word the diagnostic — only value-vs-value differences and accept-vs-reject are');
    @l.push('listed. Every entry is a Raku++ fix candidate.');
    @l.push('');
    @l.push('**' ~ @all.elems ~ '** disagreements across **' ~ %m.elems ~ '** operators.');
    @l.push('');

    @l.push('## Type mismatches by root cause');
    @l.push('');
    @l.push('These collapse hard: fixing one defect clears every row it produced.');
    @l.push('');
    @l.push('| Raku++ returns | Rakudo returns | Rows | Example expression |');
    @l.push('|---|---|---:|---|');
    for %pat.sort({ -.value }) -> $p {
        my ($a, $b) = $p.key.split("\t");
        @l.push('| `' ~ cell($a) ~ '` | `' ~ cell($b) ~ '` | ' ~ $p.value ~
                ' | `' ~ cell(%ex{$p.key}) ~ '` |');
    }
    @l.push('');

    for %cluster.sort({ -.value.elems }) -> $p {
        @l.push('## ' ~ $p.key ~ ' (' ~ $p.value.elems ~ ')');
        @l.push('');
        @l.push('| Operator | Expression | Raku++ | Rakudo |');
        @l.push('|---|---|---|---|');
        my $n = 0;
        for @($p.value) -> @d {
            @l.push('| ' ~ opname(@d[0]) ~ ' | `' ~ cell(@d[1]) ~ '` | ' ~
                    result(@d[2]) ~ ' | ' ~ result(@d[3]) ~ ' |');
            last if ++$n >= 30;
        }
        @l.push('');
        @l.push('…and ' ~ ($p.value.elems - $n) ~ ' more.') if $p.value.elems > $n;
        @l.push('');
    }

    spurt $out, @l.join("\n") ~ "\n";
    say "wrote $out — {@all.elems} divergences in {%cluster.elems} clusters";
}
