#!/usr/bin/env raku
# conformance.raku — turn the three-way example run into a work list.
#
#   rakupp tools/conformance.raku        # -> CONFORMANCE.md
#
# Reads src/data/typerun.raku (every documentation example, run on both engines
# and compared against the output the documentation asserts) and sorts the
# results into the four things a person might actually do next:
#
#   * implement a missing method
#   * fix a wrong result
#   * report a stale example upstream
#   * look at something none of the three agree on
#
# Pipes are escaped throughout: results routinely contain them.

sub cell($v --> Str) {
    my $s = $v.defined ?? ~$v !! '';
    # Some examples print raw bytes (Buf, encode, IO). Those do not survive
    # being embedded in a Markdown table — and reading them in a table would
    # tell nobody anything — so they are named rather than reproduced.
    return '«binary output»' if $s.comb.first({ .ord < 9 || (.ord >= 14 && .ord < 32)
                                                || (.ord >= 0x80 && .ord <= 0x9F) }).defined;
    $s.subst('|', '\\|', :g).subst("\n", '⏎', :g).subst("\t", ' ', :g)
}
sub clip(Str $s, Int $n --> Str) { $s.chars > $n ?? $s.substr(0, $n) ~ '…' !! $s }

sub MAIN(Str :$runs = 'src/data/typerun.raku', Str :$out = 'CONFORMANCE.md') {
    my %r = EVAL slurp $runs;
    my @runs = @(%r<runs>);

    my %tally;
    %tally{ .[2] }++ for @runs;

    # Raku++ failures, split by what would fix them.
    my %missing;      # diagnostic -> count
    my %missing-ex;
    my @wrong;
    my @drift;
    my @alldiff;
    my @rakudo;
    my %bytype;

    for @runs -> @x {
        my ($type, $idx, $verdict, $ku, $ra, $kerr) = @x[0], @x[1], @x[2], @x[3], @x[4], @x[5];
        given $verdict {
            when 'rakupp-differs' {
                %bytype{$type}++;
                if !$ku.chars && $kerr.chars {
                    my $d = $kerr.trim;
                    %missing{$d}++;
                    %missing-ex{$d} //= $type;
                }
                else { @wrong.push([$type, $ra, $ku]) }
            }
            when 'doc-drift'  { @drift.push([$type, $ra, @x[4]]) }
            when 'rakudo-differs' { @rakudo.push([$type, $ku, $ra]) }
            when 'all-differ' { @alldiff.push([$type, $ku, $ra]) }
        }
    }

    my @l;
    @l.push('# Raku++ conformance against the official documentation');
    @l.push('');
    @l.push('Generated by `tools/conformance.raku`. Every example in the Raku documentation');
    @l.push('that states an expected output was run on Raku++ and on Rakudo, and the three');
    @l.push('answers compared.');
    @l.push('');
    @l.push('| Verdict | Count | Meaning |');
    @l.push('|---|---:|---|');
    my %meaning =
        'ok'             => 'documentation, Rakudo and Raku++ all agree',
        'rakupp-differs' => 'documentation and Rakudo agree; **Raku++ is wrong**',
        'all-differ'     => 'three different answers — needs a human',
        'doc-drift'      => 'both engines agree; **the documentation is stale**',
        'rakudo-differs' => 'doc and Raku++ agree; **Rakudo does not** — usually a stale doc that Raku++ was built from',
        'not-runnable'   => 'neither engine runs it standalone (needs surrounding context)';
    for %tally.sort({ -.value }) -> $p {
        @l.push('| `' ~ $p.key ~ '` | ' ~ $p.value ~ ' | ' ~ (%meaning{$p.key} // '') ~ ' |');
    }
    @l.push('');

    @l.push('## Where Raku++ fails, by type');
    @l.push('');
    @l.push('| Type | Failing examples |');
    @l.push('|---|---:|');
    my $n = 0;
    for %bytype.sort({ -.value }) -> $p {
        @l.push('| `' ~ cell($p.key) ~ '` | ' ~ $p.value ~ ' |');
        last if ++$n >= 40;
    }
    @l.push('');

    @l.push('## Missing routines (' ~ %missing.values.sum ~ ' examples, ' ~ %missing.elems ~ ' distinct)');
    @l.push('');
    @l.push('Raku++ produced no output and reported a dispatch failure. Each line is one');
    @l.push('routine to implement.');
    @l.push('');
    @l.push('| Diagnostic | Examples | First seen on |');
    @l.push('|---|---:|---|');
    for %missing.sort({ -.value }) -> $p {
        @l.push('| ' ~ cell(clip($p.key, 90)) ~ ' | ' ~ $p.value ~ ' | `' ~ cell(%missing-ex{$p.key}) ~ '` |');
    }
    @l.push('');

    @l.push('## Wrong results (' ~ @wrong.elems ~ ')');
    @l.push('');
    @l.push('Raku++ ran the example cleanly and produced something other than what Rakudo');
    @l.push('produces. These are the substantive defects.');
    @l.push('');
    @l.push('| Type | Rakudo | Raku++ |');
    @l.push('|---|---|---|');
    $n = 0;
    for @wrong -> @w {
        @l.push('| `' ~ cell(@w[0]) ~ '` | `' ~ cell(clip(@w[1], 60)) ~ '` | `' ~ cell(clip(@w[2], 60)) ~ '` |');
        last if ++$n >= 60;
    }
    @l.push('');
    @l.push('…and ' ~ (@wrong.elems - $n) ~ ' more.') if @wrong.elems > $n;
    @l.push('');

    @l.push('## Documentation drift (' ~ @drift.elems ~ ')');
    @l.push('');
    @l.push('Both engines agree with each other and disagree with the documentation, so the');
    @l.push('documentation is the thing that is wrong. Worth reporting upstream — and worth');
    @l.push('*not* tuning Raku++ towards.');
    @l.push('');
    @l.push('| Type | Both engines produce |');
    @l.push('|---|---|');
    $n = 0;
    for @drift -> @d {
        @l.push('| `' ~ cell(@d[0]) ~ '` | `' ~ cell(clip(@d[1], 80)) ~ '` |');
        last if ++$n >= 40;
    }
    @l.push('');
    @l.push('…and ' ~ (@drift.elems - $n) ~ ' more.') if @drift.elems > $n;
    @l.push('');

    @l.push('## Raku++ agrees with the docs, Rakudo does not (' ~ @rakudo.elems ~ ')');
    @l.push('');
    @l.push('The one class where neither engine can be assumed correct. It may be a stale');
    @l.push('doc that Raku++ was built from — or a Rakudo bug that the documentation');
    @l.push('predates. **Do not resolve these by following Rakudo.** Examine each and');
    @l.push('record the finding in `src/rules/adjudications.raku`, which the site then');
    @l.push('shows on the example itself.');
    @l.push('');
    @l.push('Worked example: the documentation and Raku++ both give `1.asinh` as');
    @l.push('`0.881373587019543`; Rakudo gives `0.8813735870195429`. asinh(1) is');
    @l.push('ln(1+√2) = 0.88137358701954302523…, whose correctly-rounded double has');
    @l.push('`0.881373587019543` as its shortest round-tripping form. Raku++ is right and');
    @l.push('Rakudo is one ulp low — following Rakudo would have made Raku++ worse.');
    @l.push('');
    @l.push('| Type | Doc and Raku++ | Rakudo |');
    @l.push('|---|---|---|');
    for @rakudo -> @d {
        @l.push('| `' ~ cell(@d[0]) ~ '` | `' ~ cell(clip(@d[1], 60)) ~ '` | `' ~
                cell(clip(@d[2], 60)) ~ '` |');
    }
    @l.push('');

    spurt $out, @l.join("\n") ~ "\n";
    say "wrote $out";
    say "  missing routines : {%missing.elems} distinct";
    say "  wrong results    : {@wrong.elems}";
    say "  doc drift        : {@drift.elems}";
    say "  all differ       : {@alldiff.elems}";
    say "  rakudo differs   : {@rakudo.elems}";
}
